/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_2020();
void sub_2030();
void sub_2040();
void sub_2050();
void sub_2060();
void sub_2070();
void sub_2080();
void sub_2090();
void sub_20A0();
void sub_20B0();
void sub_20C0();
void sub_20D0();
void sub_20E0();
void sub_20F0();
void sub_2100();
void sub_2110();
void sub_2120();
void sub_2130();
void sub_2140();
void sub_2150();
void sub_2160();
void sub_2170();
void sub_2180();
void sub_2190();
void sub_21A0();
void sub_21B0();
void sub_21C0();
void sub_21D0();
void sub_21E0();
void sub_21F0();
// int __fastcall _cxa_finalize(void *);
// char *getenv(const char *name);
// int strcasecmp(const char *s1, const char *s2);
// int *__errno_location(void);
// char *strcpy(char *dest, const char *src);
// int puts(const char *s);
// ssize_t write(int fd, const void *buf, size_t n);
// size_t strlen(const char *s);
// unsigned int alarm(unsigned int seconds);
// int close(int fd);
// ssize_t read(int fd, void *buf, size_t nbytes);
// char *fgets(char *s, int n, FILE *stream);
// int strcmp(const char *s1, const char *s2);
// __sighandler_t signal(int sig, __sighandler_t handler);
// struct hostent *gethostbyname(const char *name);
// __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 strtol(const char *nptr, char **endptr, int base);
// int fflush(FILE *stream);
// __int64 __isoc99_sscanf(_QWORD, const char *, ...); weak
// __int64 __printf_chk(_QWORD, const char *, ...); weak
// FILE *fopen(const char *filename, const char *modes);
// int gethostname(char *name, size_t len);
// void __noreturn exit(int status);
// int connect(int fd, const struct sockaddr *addr, socklen_t len);
// __int64 __fprintf_chk(_QWORD, _QWORD, const char *, ...); weak
// unsigned int sleep(unsigned int seconds);
// const unsigned __int16 **__ctype_b_loc(void);
// __int64 __sprintf_chk(_QWORD, _QWORD, _QWORD, const char *, ...); weak
// int socket(int domain, int type, int protocol);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
FILE **deregister_tm_clones();
__int64 register_tm_clones();
FILE **_do_global_dtors_aux();
__int64 frame_dummy(); // weak
int __fastcall main(int argc, const char **argv, const char **envp);
__int64 __fastcall phase_1(char *a1);
unsigned __int64 __fastcall phase_2(__int64 a1);
unsigned __int64 __fastcall phase_3(__int64 a1);
__int64 __fastcall func4(__int64 a1, __int64 a2, __int64 a3);
unsigned __int64 __fastcall phase_4(__int64 a1);
_BYTE *__fastcall phase_5(_BYTE *a1);
unsigned __int64 __fastcall phase_6(__int64 a1);
__int64 __fastcall fun7(__int64 a1, int a2);
unsigned __int64 secret_phase();
void __noreturn sig_handler();
void __fastcall __noreturn invalid_phase(const char *a1);
__int64 __fastcall string_length(_BYTE *a1);
__int64 __fastcall strings_not_equal(char *a1, _BYTE *a2);
unsigned __int64 initialize_bomb();
void initialize_bomb_solve();
__int64 __fastcall blank_line(char *a1);
char *skip();
__int64 __fastcall send_msg(int a1);
void __noreturn explode_bomb();
__int64 __fastcall read_six_numbers(__int64 a1, __int64 a2);
const char *read_line();
unsigned __int64 phase_defused();
void __noreturn sigalrm_handler();
__int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3);
__int64 __fastcall submitr(const char *a1, __int16 a2, const char *a3, const char *a4, const char *a5, const char *a6, const char *a7, char *a8);
void __fastcall init_timeout(int seconds);
__int64 __fastcall init_driver(char *a1);
__int64 __fastcall driver_post(const char *a1, const char *a2, const char *a3, int a4, char *a5);
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

int dword_0 = 1179403647; // weak
_DWORD array_0[16] = { 2, 10, 6, 1, 12, 16, 9, 3, 4, 7, 14, 5, 11, 8, 15, 13 }; // weak
void *_dso_handle = &_dso_handle; // idb
char user_password[21] = "ghsPh5t1jI3KoOCDd6eC"; // weak
char userid[9] = "aydeltay"; // weak
int bomb_id = 187; // weak
_UNKNOWN n1; // weak
_UNKNOWN node1; // weak
char *host_table = "shanghai.cs.byu.edu"; // idb
char *off_7288[18] =
{
  "seattle.cs.byu.edu",
  "sanfrancisco.cs.byu.edu",
  "rome.cs.byu.edu",
  "stlouis.cs.byu.edu",
  "sydney.cs.byu.edu",
  "tokyo.cs.byu.edu",
  "peggy.cs.byu.edu",
  "spiderman.cs.byu.edu",
  "blackpanther.cs.byu.edu",
  "hawkeye.cs.byu.edu",
  "starlord.cs.byu.edu",
  "hailstorm.cs.byu.edu",
  "typhoon.cs.byu.edu",
  "alabama.cs.byu.edu",
  "hawaii.cs.byu.edu",
  "delaware.cs.byu.edu",
  "ohio.cs.byu.edu",
  "oregon.cs.byu.edu"
}; // weak
FILE *_bss_start; // idb
__int64 stdin; // weak
__int64 stderr; // weak
char completed_0; // weak
FILE *infile; // idb
int num_input_strings; // weak
char input_strings[240]; // weak
_UNKNOWN unk_7810; // weak


//----- (0000000000002000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 7E68: using guessed type __int64 _gmon_start__(void);

//----- (0000000000002020) ----------------------------------------------------
void sub_2020()
{
  JUMPOUT(0LL);
}
// 2026: control flows out of bounds to 0

//----- (0000000000002030) ----------------------------------------------------
void sub_2030()
{
  sub_2020();
}

//----- (0000000000002040) ----------------------------------------------------
void sub_2040()
{
  sub_2020();
}

//----- (0000000000002050) ----------------------------------------------------
void sub_2050()
{
  sub_2020();
}

//----- (0000000000002060) ----------------------------------------------------
void sub_2060()
{
  sub_2020();
}

//----- (0000000000002070) ----------------------------------------------------
void sub_2070()
{
  sub_2020();
}

//----- (0000000000002080) ----------------------------------------------------
void sub_2080()
{
  sub_2020();
}

//----- (0000000000002090) ----------------------------------------------------
void sub_2090()
{
  sub_2020();
}

//----- (00000000000020A0) ----------------------------------------------------
void sub_20A0()
{
  sub_2020();
}

//----- (00000000000020B0) ----------------------------------------------------
void sub_20B0()
{
  sub_2020();
}

//----- (00000000000020C0) ----------------------------------------------------
void sub_20C0()
{
  sub_2020();
}

//----- (00000000000020D0) ----------------------------------------------------
void sub_20D0()
{
  sub_2020();
}

//----- (00000000000020E0) ----------------------------------------------------
void sub_20E0()
{
  sub_2020();
}

//----- (00000000000020F0) ----------------------------------------------------
void sub_20F0()
{
  sub_2020();
}

//----- (0000000000002100) ----------------------------------------------------
void sub_2100()
{
  sub_2020();
}

//----- (0000000000002110) ----------------------------------------------------
void sub_2110()
{
  sub_2020();
}

//----- (0000000000002120) ----------------------------------------------------
void sub_2120()
{
  sub_2020();
}

//----- (0000000000002130) ----------------------------------------------------
void sub_2130()
{
  sub_2020();
}

//----- (0000000000002140) ----------------------------------------------------
void sub_2140()
{
  sub_2020();
}

//----- (0000000000002150) ----------------------------------------------------
void sub_2150()
{
  sub_2020();
}

//----- (0000000000002160) ----------------------------------------------------
void sub_2160()
{
  sub_2020();
}

//----- (0000000000002170) ----------------------------------------------------
void sub_2170()
{
  sub_2020();
}

//----- (0000000000002180) ----------------------------------------------------
void sub_2180()
{
  sub_2020();
}

//----- (0000000000002190) ----------------------------------------------------
void sub_2190()
{
  sub_2020();
}

//----- (00000000000021A0) ----------------------------------------------------
void sub_21A0()
{
  sub_2020();
}

//----- (00000000000021B0) ----------------------------------------------------
void sub_21B0()
{
  sub_2020();
}

//----- (00000000000021C0) ----------------------------------------------------
void sub_21C0()
{
  sub_2020();
}

//----- (00000000000021D0) ----------------------------------------------------
void sub_21D0()
{
  sub_2020();
}

//----- (00000000000021E0) ----------------------------------------------------
void sub_21E0()
{
  sub_2020();
}

//----- (00000000000021F0) ----------------------------------------------------
void sub_21F0()
{
  sub_2020();
}

//----- (00000000000023E0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, 0LL, 0LL, a3, &v5);
  __halt();
}
// 23EA: positive sp value 8 has been found
// 23F1: variable 'v3' is possibly undefined

//----- (0000000000002410) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &_bss_start;
}

//----- (0000000000002440) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}

//----- (0000000000002480) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( !completed_0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 76A8: using guessed type char completed_0;

//----- (00000000000024C0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 24C0: using guessed type __int64 frame_dummy();

//----- (00000000000024C9) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  char *line; // rax
  const char *v4; // rax
  const char *v5; // rax
  const char *v6; // rax
  char *v7; // rax
  const char *v8; // rax

  if ( argc == 1 )
  {
    infile = (FILE *)stdin;
  }
  else
  {
    if ( argc != 2 )
    {
      __printf_chk(1LL, "Usage: %s [<input_file>]\n", *argv);
      exit(8);
    }
    infile = fopen(argv[1], "r");
    if ( !infile )
    {
      __printf_chk(1LL, "%s: Error: Couldn't open %s\n", *argv, argv[1]);
      exit(8);
    }
  }
  initialize_bomb();
  puts("Welcome to my fiendish little bomb. You have 6 phases with");
  puts("which to blow yourself up. Have a nice day!");
  line = (char *)read_line();
  phase_1(line);
  phase_defused();
  puts("Phase 1 defused. How about the next one?");
  v4 = read_line();
  phase_2((__int64)v4);
  phase_defused();
  puts("That's number 2.  Keep going!");
  v5 = read_line();
  phase_3((__int64)v5);
  phase_defused();
  puts("Halfway there!");
  v6 = read_line();
  phase_4((__int64)v6);
  phase_defused();
  puts("So you got that one.  Try this one.");
  v7 = (char *)read_line();
  phase_5(v7);
  phase_defused();
  puts("Good work!  On to the next...");
  v8 = read_line();
  phase_6((__int64)v8);
  phase_defused();
  return 0;
}
// 2340: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);
// 7690: using guessed type __int64 stdin;

//----- (0000000000002627) ----------------------------------------------------
__int64 __fastcall phase_1(char *a1)
{
  __int64 result; // rax

  result = strings_not_equal(a1, "There are rumors on the internets.");
  if ( (_DWORD)result )
    explode_bomb();
  return result;
}

//----- (000000000000264B) ----------------------------------------------------
unsigned __int64 __fastcall phase_2(__int64 a1)
{
  int *v1; // rbp
  int i; // ebx
  int v4[6]; // [rsp+0h] [rbp-38h] BYREF
  unsigned __int64 v5; // [rsp+18h] [rbp-20h]

  v5 = __readfsqword(0x28u);
  read_six_numbers(a1, (__int64)v4);
  if ( v4[0] < 0 )
    
    explode_bomb();
  v1 = v4;
  for ( i = 1; i != 6; ++i )
  {
    if ( v1[1] != *v1 + i )
      explode_bomb();
    ++v1;
  }
  return v5 - __readfsqword(0x28u);
}

//----- (00000000000026BD) ----------------------------------------------------
unsigned __int64 __fastcall phase_3(__int64 a1)
{
  char v1; // al
  unsigned __int64 result; // rax
  char v3; // [rsp+Fh] [rbp-19h] BYREF
  int v4; // [rsp+10h] [rbp-18h] BYREF
  int v5; // [rsp+14h] [rbp-14h] BYREF
  unsigned __int64 v6; // [rsp+18h] [rbp-10h]

  // 0 f 622

  v6 = __readfsqword(0x28u);
  if ( (int)__isoc99_sscanf(a1, "%d %c %d", &v4, &v3, &v5) <= 2 )
    explode_bomb();
  switch ( v4 )
  {
    case 0:
      v1 = 102;
      if ( v5 != 622 )
        explode_bomb();
      return result;
    case 1:
      v1 = 112;
      if ( v5 != 689 )
        explode_bomb();
      return result;
    case 2:
      v1 = 109;
      if ( v5 != 142 )
        explode_bomb();
      return result;
    case 3:
      v1 = 107;
      if ( v5 != 839 )
        explode_bomb();
      return result;
    case 4:
      v1 = 121;
      if ( v5 != 531 )
        explode_bomb();
      return result;
    case 5:
      v1 = 106;
      if ( v5 != 283 )
        explode_bomb();
      return result;
    case 6:
      v1 = 110;
      if ( v5 != 964 )
        explode_bomb();
      return result;
    case 7:
      v1 = 100;
      if ( v5 != 84 )
        explode_bomb();
      return result;
    default:
      explode_bomb();
  }
  if ( v3 != v1 )
    explode_bomb();
  return v6 - __readfsqword(0x28u);
}
// 2330: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);

//----- (0000000000002837) ----------------------------------------------------
__int64 __fastcall func4(__int64 a1, __int64 a2, __int64 a3)
{
  int v3; // ebx

  v3 = a2 + ((int)a3 - (int)a2) / 2;
  if ( v3 > (int)a1 )
  {
    v3 += func4(a1, a2, (unsigned int)(v3 - 1));
  }
  else if ( v3 < (int)a1 )
  {
    v3 += func4(a1, (unsigned int)(v3 + 1), a3);
  }
  return (unsigned int)v3;
}

//----- (000000000000286D) ----------------------------------------------------
unsigned __int64 __fastcall phase_4(__int64 a1)
{
  unsigned int v2; // [rsp+0h] [rbp-18h] BYREF
  int v3; // [rsp+4h] [rbp-14h] BYREF
  unsigned __int64 v4; // [rsp+8h] [rbp-10h]

  v4 = __readfsqword(0x28u);
  if ( (unsigned int)__isoc99_sscanf(a1, "%d %d", &v2, &v3) != 2 || v2 > 0xE )
    explode_bomb();
  if ( (unsigned int)func4(v2, 0LL, 14LL) != 10 || v3 != 10 )
    explode_bomb();
  return v4 - __readfsqword(0x28u);
}
// 2330: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);

//----- (00000000000028E6) ----------------------------------------------------
_BYTE *__fastcall phase_5(_BYTE *a1)
{
  _BYTE *result; // rax
  _BYTE *v2; // rdi
  int v3; // ecx

  if ( (unsigned int)string_length(a1) != 6 )
    explode_bomb();
  result = a1;
  v2 = a1 + 6;
  v3 = 0;
  do
    v3 += array_0[*result++ & 0xF];
  while ( result != v2 );
  if ( v3 != 44 )
    explode_bomb();
  return result;
}
// 41E0: using guessed type _DWORD array_0[16];

//----- (0000000000002932) ----------------------------------------------------
unsigned __int64 __fastcall phase_6(__int64 a1)
{
  int *v1; // r13
  __int64 i; // r14
  __int64 v3; // rbx
  __int64 j; // rsi
  int v5; // ecx
  int v6; // eax
  _QWORD *v7; // rdx
  __int64 v8; // rbx
  __int64 v9; // rax
  __int64 v10; // rdx
  __int64 v11; // rax
  __int64 v12; // rdx
  __int64 v13; // rax
  int v14; // ebp
  int v16[8]; // [rsp+0h] [rbp-88h] BYREF
  __int64 v17; // [rsp+20h] [rbp-68h]
  __int64 v18; // [rsp+28h] [rbp-60h]
  __int64 v19; // [rsp+30h] [rbp-58h]
  __int64 v20; // [rsp+38h] [rbp-50h]
  __int64 v21; // [rsp+40h] [rbp-48h]
  __int64 v22; // [rsp+48h] [rbp-40h]
  unsigned __int64 v23; // [rsp+58h] [rbp-30h]

  v23 = __readfsqword(0x28u);
  v1 = v16;
  read_six_numbers(a1, (__int64)v16);
  for ( i = 1LL; ; ++i )
  {
    if ( (unsigned int)(*v1 - 1) > 5 )
      explode_bomb();
    if ( (int)i > 5 )
      break;
    v3 = i;
    do
    {
      if ( *v1 == v16[v3] )
        explode_bomb();
      ++v3;
    }
    while ( (int)v3 <= 5 );
    ++v1;
  }
  for ( j = 0LL; j != 6; ++j )
  {
    v5 = v16[j];
    v6 = 1;
    v7 = &node1;
    if ( v5 > 1 )
    {
      do
      {
        v7 = (_QWORD *)v7[1];
        ++v6;
      }
      while ( v6 != v5 );
    }
    *(&v17 + j) = (__int64)v7;
  }
  v8 = v17;
  v9 = v18;
  *(_QWORD *)(v17 + 8) = v18;
  v10 = v19;
  *(_QWORD *)(v9 + 8) = v19;
  v11 = v20;
  *(_QWORD *)(v10 + 8) = v20;
  v12 = v21;
  *(_QWORD *)(v11 + 8) = v21;
  v13 = v22;
  *(_QWORD *)(v12 + 8) = v22;
  *(_QWORD *)(v13 + 8) = 0LL;
  v14 = 5;
  do
  {
    if ( *(_DWORD *)v8 > **(_DWORD **)(v8 + 8) )
      explode_bomb();
    v8 = *(_QWORD *)(v8 + 8);
    --v14;
  }
  while ( v14 );
  return v23 - __readfsqword(0x28u);
}
// 2932: using guessed type int var_88[8];

//----- (0000000000002A5A) ----------------------------------------------------
__int64 __fastcall fun7(__int64 a1, int a2)
{
  __int64 result; // rax

  if ( !a1 )
    return 0xFFFFFFFFLL;
  if ( *(_DWORD *)a1 > a2 )
    return 2 * (unsigned int)fun7(*(_QWORD *)(a1 + 8));
  result = 0LL;
  if ( *(_DWORD *)a1 != a2 )
    return 2 * (unsigned int)fun7(*(_QWORD *)(a1 + 16)) + 1;
  return result;
}

//----- (0000000000002A9B) ----------------------------------------------------
unsigned __int64 secret_phase()
{
  const char *line; // rax
  int v1; // ebx

  line = read_line();
  v1 = strtol(line, 0LL, 10);
  if ( (unsigned int)(v1 - 1) > 0x3E8 )
    explode_bomb();
  if ( (unsigned int)fun7((__int64)&n1, v1) != 5 )
    explode_bomb();
  puts("Wow! You've defused the secret stage!");
  return phase_defused();
}

//----- (0000000000002AF7) ----------------------------------------------------
void __noreturn sig_handler()
{
  puts("So you think you can stop the bomb with ctrl-c, do you?");
  sleep(3u);
  __printf_chk(1LL, "Well...");
  fflush(_bss_start);
  sleep(1u);
  puts("OK. :-)");
  exit(16);
}
// 2340: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);

//----- (0000000000002B59) ----------------------------------------------------
void __fastcall __noreturn invalid_phase(const char *a1)
{
  __printf_chk(1LL, "Invalid phase%s\n", a1);
  exit(8);
}
// 2340: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);

//----- (0000000000002B86) ----------------------------------------------------
__int64 __fastcall string_length(_BYTE *a1)
{
  __int64 result; // rax

  if ( !*a1 )
    return 0LL;
  LODWORD(result) = 0;
  do
  {
    ++a1;
    result = (unsigned int)(result + 1);
  }
  while ( *a1 );
  return result;
}

//----- (0000000000002BA7) ----------------------------------------------------
__int64 __fastcall strings_not_equal(char *a1, _BYTE *a2)
{
  int v2; // r12d
  int v3; // edx
  __int64 result; // rax
  char v5; // dl
  __int64 v6; // rax

  v2 = string_length(a1);
  v3 = string_length(a2);
  result = 1LL;
  if ( v2 == v3 )
  {
    v5 = *a1;
    if ( *a1 )
    {
      v6 = 0LL;
      while ( a2[v6] == v5 )
      {
        v5 = a1[++v6];
        if ( !v5 )
          return 0LL;
      }
      return 1LL;
    }
    else
    {
      return 0LL;
    }
  }
  return result;
}

//----- (0000000000002C07) ----------------------------------------------------
unsigned __int64 initialize_bomb()
{
  const char *v0; // rdi
  char **v1; // rbx
  char v3[64]; // [rsp+0h] [rbp-2068h] BYREF
  char v4[24]; // [rsp+40h] [rbp-2028h] BYREF
  unsigned __int64 v5; // [rsp+2048h] [rbp-20h]

  v5 = __readfsqword(0x28u);
  signal(2, (__sighandler_t)sig_handler);
  if ( gethostname(v3, 0x40uLL) )
  {
    puts("Initialization error: Running on an illegal host [1]");
    exit(8);
  }
  v0 = host_table;
  v1 = off_7288;
  if ( !host_table )
  {
LABEL_5:
    puts("Initialization error: Running on an illegal host [2]");
    exit(8);
  }
  while ( strcasecmp(v0, v3) )
  {
    v0 = *v1++;
    if ( !v0 )
      goto LABEL_5;
  }
  if ( (int)init_driver(v4) < 0 )
  {
    __printf_chk(1LL, "Initialization error:\n%s\n", v4);
    exit(8);
  }
  return v5 - __readfsqword(0x28u);
}
// 2340: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);
// 7288: using guessed type char *off_7288[18];

//----- (0000000000002D0E) ----------------------------------------------------
void initialize_bomb_solve()
{
  ;
}

//----- (0000000000002D13) ----------------------------------------------------
__int64 __fastcall blank_line(char *a1)
{
  char v2; // bl

  while ( 1 )
  {
    v2 = *a1;
    if ( !*a1 )
      break;
    ++a1;
    if ( ((*__ctype_b_loc())[v2] & 0x2000) == 0 )
      return 0LL;
  }
  return 1LL;
}

//----- (0000000000002D52) ----------------------------------------------------
char *skip()
{
  char *v0; // rax
  char *v1; // rbx

  do
  {
    v0 = fgets(&input_strings[80 * num_input_strings], 80, infile);
    v1 = v0;
  }
  while ( v0 && (unsigned int)blank_line(v0) );
  return v1;
}
// 7710: using guessed type int num_input_strings;

//----- (0000000000002DA4) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
__int64 __fastcall send_msg(int a1)
{
  const char *v1; // r9
  char v3[16]; // [rsp+0h] [rbp-4008h] BYREF
  __int64 v4; // [rsp+10h] [rbp-3FF8h] BYREF
  __int64 v5; // [rsp+1010h] [rbp-2FF8h] BYREF
  char v6[16]; // [rsp+1FF0h] [rbp-2018h] BYREF
  char v7[4096]; // [rsp+2000h] [rbp-2008h] BYREF
  __int64 v8; // [rsp+3FF8h] [rbp-10h]
  unsigned __int64 retaddr; // [rsp+4008h] [rbp+0h]

  while ( &v4 != &v5 - 2048 )
    ;
  retaddr = __readfsqword(0x28u);
  v1 = "defused";
  if ( !a1 )
    v1 = "exploded";
  __sprintf_chk(
    v3,
    1LL,
    0x2000LL,
    "%d:%s:%d:%s",
    (unsigned int)bomb_id,
    v1,
    (unsigned int)num_input_strings,
    &input_strings[80 * num_input_strings - 80]);
  if ( (int)driver_post(userid, user_password, v3, 0, v7) < 0 )
  {
    puts(v6);
    exit(0);
  }
  return v8 - __readfsqword(0x28u);
}
// 2E79: positive sp value 2FF0 has been found
// 23C0: using guessed type __int64 __sprintf_chk(_QWORD, _QWORD, _QWORD, const char *, ...);
// 7144: using guessed type int bomb_id;
// 7710: using guessed type int num_input_strings;
// 2DA4: using guessed type char anonymous_0[16];
// 2DA4: using guessed type char anonymous_1[4096];

//----- (0000000000002E96) ----------------------------------------------------
void __noreturn explode_bomb()
{
  puts("\nBOOM!!!");
  puts("The bomb has blown up.");
  send_msg(0);
  puts("Your instructor has been notified.");
  exit(8);
}

//----- (0000000000002ED8) ----------------------------------------------------
__int64 __fastcall read_six_numbers(__int64 a1, __int64 a1)
{
  __int64 result; // rax

  result = __isoc99_sscanf(a1, "%d %d %d %d %d %d", a2, a2 + 4, a2 + 8, a2 + 12, a2 + 16, a2 + 20);    
  if ( (int)result <= 5 )
    // explode_bomb();
  return result;
}
// 2330: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);

//----- (0000000000002F1D) ----------------------------------------------------
const char *read_line()
{
  int v0; // ebp
  const char *v1; // rbx
  int v2; // eax
  int v4; // eax

  if ( !skip() )
  {
    if ( infile == (FILE *)stdin )
    {
      puts("Error: Premature EOF on stdin");
      exit(8);
    }
    if ( getenv("GRADE_BOMB") )
      exit(0);
    infile = (FILE *)stdin;
    if ( !skip() )
    {
      puts("Error: Premature EOF on stdin");
      exit(0);
    }
  }
  v0 = num_input_strings;
  v1 = &input_strings[80 * num_input_strings];
  v2 = strlen(v1);
  if ( v2 > 78 )
  {
    puts("Error: Input line too long");
    v4 = num_input_strings++;
    strcpy(&input_strings[80 * v4], "***truncated***");
    explode_bomb();
  }
  input_strings[80 * v0 - 1 + v2] = 0;
  num_input_strings = v0 + 1;
  return v1;
}
// 7690: using guessed type __int64 stdin;
// 7710: using guessed type int num_input_strings;

//----- (0000000000003055) ----------------------------------------------------
unsigned __int64 phase_defused()
{
  char v1; // [rsp+8h] [rbp-70h] BYREF
  char v2; // [rsp+Ch] [rbp-6Ch] BYREF
  char v3[88]; // [rsp+10h] [rbp-68h] BYREF
  unsigned __int64 v4; // [rsp+68h] [rbp-10h]

  v4 = __readfsqword(0x28u);
  send_msg(1);
  if ( num_input_strings == 6 )
  {
    if ( (unsigned int)__isoc99_sscanf(&unk_7810, "%d %d %s", &v1, &v2, v3) == 3
      && !(unsigned int)strings_not_equal(v3, "DrEvil") )
    {
      puts("Curses, you've found the secret phase!");
      puts("But finding it and solving it are quite different...");
      secret_phase();
    }
    puts("Congratulations! You've defused the bomb!");
    puts("Your instructor has been notified and will verify your solution.");
  }
  return v4 - __readfsqword(0x28u);
}
// 2330: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);
// 7710: using guessed type int num_input_strings;
// 3055: using guessed type char var_68[88];

//----- (000000000000311D) ----------------------------------------------------
void __noreturn sigalrm_handler()
{
  __fprintf_chk(stderr, 1LL, "Program timed out after %d seconds\n", 0LL);
  exit(1);
}
// 2390: using guessed type __int64 __fprintf_chk(_QWORD, _QWORD, const char *, ...);
// 76A0: using guessed type __int64 stderr;

//----- (0000000000003153) ----------------------------------------------------
__int64 __fastcall rio_readlineb(__int64 a1, _BYTE *a2, unsigned __int64 a3)
{
  _BYTE *v3; // r12
  __int64 v4; // r14
  int v5; // r13d
  void *v6; // rbp
  int v7; // eax
  int v8; // edx
  char *v9; // rax
  char v10; // cl
  int v11; // eax
  __int64 result; // rax

  v3 = a2;
  if ( a3 <= 1 )
  {
    v5 = 1;
LABEL_18:
    *v3 = 0;
    return v5;
  }
  else
  {
    v4 = (__int64)&a2[a3 - 1];
    v5 = 1;
    v6 = (void *)(a1 + 16);
    while ( 1 )
    {
      v8 = *(_DWORD *)(a1 + 4);
      if ( v8 <= 0 )
        break;
LABEL_7:
      v9 = *(char **)(a1 + 8);
      v10 = *v9;
      *(_QWORD *)(a1 + 8) = v9 + 1;
      *(_DWORD *)(a1 + 4) = v8 - 1;
      *v3++ = v10;
      if ( v10 == 10 )
        goto LABEL_18;
      ++v5;
      if ( v3 == (_BYTE *)v4 )
      {
        v3 = (_BYTE *)v4;
        goto LABEL_18;
      }
    }
    while ( 1 )
    {
      v7 = read(*(_DWORD *)a1, v6, 0x2000uLL);
      v8 = v7;
      *(_DWORD *)(a1 + 4) = v7;
      if ( v7 >= 0 )
        break;
      if ( *__errno_location() != 4 )
      {
        v11 = -1;
        goto LABEL_13;
      }
    }
    if ( v7 )
    {
      *(_QWORD *)(a1 + 8) = v6;
      goto LABEL_7;
    }
    v11 = 0;
LABEL_13:
    if ( v11 )
    {
      return -1LL;
    }
    else
    {
      result = 0LL;
      if ( v5 != 1 )
        goto LABEL_18;
    }
  }
  return result;
}

//----- (000000000000321F) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
__int64 __fastcall submitr(
        const char *a1,
        __int16 a2,
        const char *a3,
        const char *a4,
        const char *a5,
        const char *a6,
        const char *a7,
        char *a8)
{
  const char *v8; // rbx
  int v9; // eax
  int v10; // r12d
  struct hostent *v11; // rax
  size_t v12; // rbp
  size_t v13; // r14
  size_t v14; // r13
  int v15; // eax
  __int64 v16; // r13
  char *v17; // rbp
  __int64 v18; // r14
  int v20; // r8d
  char *i; // rbp
  size_t v22; // rbx
  ssize_t v23; // rax
  const char *v24; // [rsp-70h] [rbp-A0A0h]
  const char *v25; // [rsp-68h] [rbp-A098h]
  const char *v26; // [rsp-60h] [rbp-A090h]
  const char *v27; // [rsp-58h] [rbp-A088h]
  unsigned int v28; // [rsp-3Ch] [rbp-A06Ch] BYREF
  struct sockaddr v29; // [rsp-38h] [rbp-A068h] BYREF
  _DWORD v30[2]; // [rsp-28h] [rbp-A058h] BYREF
  __int64 *v31; // [rsp-20h] [rbp-A050h]
  __int64 v32; // [rsp-18h] [rbp-A048h] BYREF
  char v33; // [rsp+0h] [rbp-A030h] BYREF
  __int64 v34; // [rsp+1000h] [rbp-9030h] BYREF
  char v35[8192]; // [rsp+1FE8h] [rbp-8048h] BYREF
  char v36[8192]; // [rsp+3FE8h] [rbp-6048h] BYREF
  __int64 v37; // [rsp+5FE8h] [rbp-4048h] BYREF
  char v38[4008]; // [rsp+7FE8h] [rbp-2048h] BYREF
  unsigned __int64 v39; // [rsp+9FF0h] [rbp-40h]

  while ( &v33 != (char *)(&v34 - 5120) )
    ;
  v24 = a3;
  v25 = a4;
  v27 = a5;
  v26 = a6;
  v8 = a7;
  v39 = __readfsqword(0x28u);
  v28 = 0;
  v9 = socket(2, 1, 0);
  if ( v9 < 0 )
  {
    strcpy(a8, "Error: Client unable to create socket");
    return 0xFFFFFFFFLL;
  }
  v10 = v9;
  v11 = gethostbyname(a1);
  if ( !v11 )
  {
    strcpy(a8, "Error: DNS is unable to resolve server address");
    close(v10);
    return 0xFFFFFFFFLL;
  }
  *(_QWORD *)&v29.sa_family = 2LL;
  *(_QWORD *)&v29.sa_data[6] = 0LL;
  __memmove_chk(&v29.sa_data[2], *v11->h_addr_list, v11->h_length, 12LL);
  *(_WORD *)v29.sa_data = __ROL2__(a2, 8);
  if ( connect(v10, &v29, 0x10u) < 0 )
  {
    strcpy(a8, "Error: Unable to connect to the server");
    close(v10);
    return 0xFFFFFFFFLL;
  }
  v12 = strlen(a7);
  v13 = strlen(v24);
  v14 = strlen(v25);
  if ( 3 * v12 + strlen(v26) + v13 + v14 + 128 > 0x2000 )
  {
    strcpy(a8, "Error: Result string too large. Increase SUBMITR_MAXBUF");
    close(v10);
    return 0xFFFFFFFFLL;
  }
  memset(v36, 0, sizeof(v36));
  v15 = strlen(a7);
  if ( v15 )
  {
    v16 = (__int64)&a7[v15 - 1 + 1];
    v17 = v36;
    v18 = 0x2000000000FFD9LL;
    do
    {
      v20 = *(unsigned __int8 *)v8;
      if ( (unsigned __int8)(v20 - 42) <= 0x35u && _bittest64(&v18, (unsigned int)(v20 - 42))
        || (unsigned __int8)((v20 & 0xDF) - 65) <= 0x19u )
      {
        *v17++ = v20;
      }
      else if ( (_BYTE)v20 == 32 )
      {
        *v17++ = 43;
      }
      else
      {
        if ( (unsigned __int8)(v20 - 32) > 0x5Fu && (_BYTE)v20 != 9 )
        {
          strcpy(a8, "Error: Result string contains an illegal or unprintable character.");
          close(v10);
          return 0xFFFFFFFFLL;
        }
        __sprintf_chk(v38, 1LL, 8LL, "%%%02X", (unsigned __int8)v20);
        *v17 = v38[0];
        v17[1] = v38[1];
        v17[2] = v38[2];
        v17 += 3;
      }
      ++v8;
    }
    while ( v8 != (const char *)v16 );
  }
  __sprintf_chk(
    v35,
    1LL,
    0x2000LL,
    "GET /%s/submitr.pl/?userid=%s&userpwd=%s&lab=%s&result=%s&submit=submit HTTP/1.0\r\n\r\n",
    v24,
    v25,
    v27,
    v26,
    v36);
  v22 = strlen(v35);
  for ( i = v35; v22; v22 -= v23 )
  {
    v23 = write(v10, i, v22);
    if ( v23 <= 0 )
    {
      if ( *__errno_location() != 4 )
      {
        strcpy(a8, "Error: Client unable to write to the server");
        close(v10);
        return 0xFFFFFFFFLL;
      }
      v23 = 0LL;
    }
    i += v23;
  }
  v30[0] = v10;
  v30[1] = 0;
  v31 = &v32;
  if ( rio_readlineb((__int64)v30, v35, 0x2000uLL) <= 0 )
  {
    strcpy(a8, "Error: Client unable to read first header from server");
    close(v10);
    return 0xFFFFFFFFLL;
  }
  else
  {
    __isoc99_sscanf(v35, "%s %d %[a-zA-z ]", &v37, &v28, v38);
    if ( v28 == 200 )
    {
      while ( strcmp(v35, "\r\n") )
      {
        if ( rio_readlineb((__int64)v30, v35, 0x2000uLL) <= 0 )
        {
          strcpy(a8, "Error: Client unable to read headers from server");
          close(v10);
          return 0xFFFFFFFFLL;
        }
      }
      if ( rio_readlineb((__int64)v30, v35, 0x2000uLL) <= 0 )
      {
        strcpy(a8, "Error: Client unable to read status message from server");
        close(v10);
        return 0xFFFFFFFFLL;
      }
      else
      {
        strcpy(a8, v35);
        close(v10);
        return (unsigned int)-(strcmp(a8, "OK") != 0);
      }
    }
    else
    {
      __sprintf_chk(a8, 1LL, -1LL, "Error: HTTP request failed with error %d: %s", v28, v38);
      close(v10);
      return 0xFFFFFFFFLL;
    }
  }
}
// 3737: positive sp value 9000 has been found
// 2300: using guessed type __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 2330: using guessed type __int64 __isoc99_sscanf(_QWORD, const char *, ...);
// 23C0: using guessed type __int64 __sprintf_chk(_QWORD, _QWORD, _QWORD, const char *, ...);

//----- (0000000000003A23) ----------------------------------------------------
void __fastcall init_timeout(int seconds)
{
  unsigned int v1; // eax

  if ( seconds )
  {
    signal(14, (__sighandler_t)sigalrm_handler);
    v1 = 0;
    if ( seconds >= 0 )
      v1 = seconds;
    alarm(v1);
  }
}

//----- (0000000000003A53) ----------------------------------------------------
__int64 __fastcall init_driver(char *a1)
{
  int v1; // eax
  int v2; // ebx
  struct hostent *v3; // rax
  struct sockaddr v5; // [rsp+0h] [rbp-38h] BYREF
  unsigned __int64 v6; // [rsp+18h] [rbp-20h]

  v6 = __readfsqword(0x28u);
  signal(13, (__sighandler_t)((char *)&dword_0 + 1));
  signal(29, (__sighandler_t)((char *)&dword_0 + 1));
  signal(29, (__sighandler_t)((char *)&dword_0 + 1));
  v1 = socket(2, 1, 0);
  if ( v1 < 0 )
  {
    strcpy(a1, "Error: Client unable to create socket");
    return 0xFFFFFFFFLL;
  }
  else
  {
    v2 = v1;
    v3 = gethostbyname("cs224.byu.edu");
    if ( v3 )
    {
      *(_QWORD *)&v5.sa_family = 2LL;
      *(_QWORD *)&v5.sa_data[6] = 0LL;
      __memmove_chk(&v5.sa_data[2], *v3->h_addr_list, v3->h_length, 12LL);
      *(_WORD *)v5.sa_data = 28219;
      if ( connect(v2, &v5, 0x10u) < 0 )
      {
        __sprintf_chk(a1, 1LL, -1LL, "Error: Unable to connect to server %s", "cs224.byu.edu");
        close(v2);
        return 0xFFFFFFFFLL;
      }
      else
      {
        close(v2);
        strcpy(a1, "OK");
        return 0LL;
      }
    }
    else
    {
      strcpy(a1, "Error: DNS is unable to resolve server address");
      close(v2);
      return 0xFFFFFFFFLL;
    }
  }
}
// 0: using guessed type int dword_0;
// 2300: using guessed type __int64 __fastcall __memmove_chk(_QWORD, _QWORD, _QWORD, _QWORD);
// 23C0: using guessed type __int64 __sprintf_chk(_QWORD, _QWORD, _QWORD, const char *, ...);

//----- (0000000000003C48) ----------------------------------------------------
__int64 __fastcall driver_post(const char *a1, const char *a2, const char *a3, int a4, char *a5)
{
  if ( a4 )
  {
    __printf_chk(1LL, "\nAUTORESULT_STRING=%s\n", a3);
    strcpy(a5, "OK");
    return 0LL;
  }
  else if ( a1 && *a1 )
  {
    return submitr("cs224.byu.edu", 15214, "csapp", a1, a2, "W24", a3, a5);
  }
  else
  {
    strcpy(a5, "OK");
    return 0LL;
  }
}
// 2340: using guessed type __int64 __printf_chk(_QWORD, const char *, ...);

//----- (0000000000003CC0) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=128 queued=66 decompiled=66 lumina nreq=0 worse=0 better=0
// ALL OK, 66 function(s) have been successfully decompiled
